name: Deploy Website to GCP

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: githubaction-deploy-staticcode
  REGION: us-central1
  SERVICE_NAME: mywebsite

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/759899501179/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@githubaction-deploy-staticcode.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud auth configure-docker

      - run: |
          cat <<EOF > Dockerfile
          FROM nginx:alpine
          COPY . /usr/share/nginx/html
          EXPOSE 80
          CMD ["nginx", "-g", "daemon off;"]
          EOF

      - run: docker build -t us-docker.pkg.dev/${{ env.PROJECT_ID }}/myrepo/${{ env.SERVICE_NAME }} .

      - run: docker push us-docker.pkg.dev/${{ env.PROJECT_ID }}/myrepo/${{ env.SERVICE_NAME }}

      - run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image us-docker.pkg.dev/${{ env.PROJECT_ID }}/myrepo/${{ env.SERVICE_NAME }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated